export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_TEN_COUNTRIES = 'GET_TEN_COUNTRIES'
export const GET_NINE_COUNTRIES = 'GET_NINE_COUNTRIES'
export const GET_BY_NAME = 'GET_BY_NAME'
export const GET_ALL = 'GET_ALL'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'
export const GET_BY_ID = 'GET_BY_ID'
export const FILTER = 'FILTER'
export const GET_DB = 'GET_DB'
export const GET_COUNTRIES_NAMES = 'GET_COUNTRIES_NAMES'

